package com.solitech.bitcoincorenode.core.node

import com.solitech.bitcoincorenode.core.model.BitcoinNetwork
import java.io.File

/**
 * Builds the `bitcoin.conf` for the embedded node.
 *
 * Bitcoin Core's defaults are tuned for a machine that is plugged in, has a
 * fan, and does not have an owner who notices when their battery drains by
 * lunchtime. Nearly every value here is a deliberate departure from those
 * defaults, and each one is justified inline — because in six months somebody
 * (possibly you) will read `maxconnections=12` and want to "fix" it back to
 * 125, and the comment is the only thing standing between them and a phone
 * that gets warm in a pocket.
 */
data class NodeConfig(
    val network: BitcoinNetwork = BitcoinNetwork.MAIN,
    val rpcPort: Int = 8332,
    /**
     * Megabytes of block data to RETAIN. 0 disables pruning (don't, on a phone).
     *
     * ## This caps storage, not bandwidth
     *
     * The single most misunderstood setting in Bitcoin Core. A pruned node
     * still downloads and validates *every block from genesis* -- roughly
     * 700 GB at present -- it simply deletes them after checking, keeping only
     * the most recent `pruneMb`. Setting this to 5 GB does not mean a 5 GB
     * download; it means a 5 GB resting footprint after a 700 GB one.
     *
     * The only way to avoid that download is assumeutxo: load a UTXO snapshot
     * (~11 GB), become usable at the tip immediately, and let the background
     * chainstate fill in history afterwards. The onboarding and node screens
     * say this in plain words, because a user who starts an IBD on mobile data
     * expecting a 5 GB transfer is going to have a very bad month.
     */
    val pruneMb: Int = 20_000,
    /** UTXO cache in MB. The single biggest lever on sync speed and on RAM. */
    val dbCacheMb: Int = 450,
    /** Script verification threads. */
    val parallelScriptChecks: Int = 2,
    val maxConnections: Int = 12,
    val maxMempoolMb: Int = 100,
    /** Skip transaction relay entirely. Cuts mobile data by roughly 10x. */
    val blocksOnly: Boolean = false,
    val blockFilterIndex: Boolean = true,
    val useTor: Boolean = false,
    val torSocksPort: Int = 9050,
    val torOnly: Boolean = false,
    /** Accept inbound connections. Off: a phone behind CGNAT helps nobody. */
    val listen: Boolean = false,
    val extraArgs: List<String> = emptyList(),
) {

    fun render(): String = buildString {
        appendLine("# Generated by Bitcoin Core Node. Edits here are overwritten on start.")
        appendLine("# To add your own settings, use Settings -> Advanced -> Extra arguments.")
        appendLine()

        appendLine("# --- Network ---")
        when (network) {
            BitcoinNetwork.MAIN -> appendLine("# mainnet (default)")
            BitcoinNetwork.TEST -> appendLine("testnet=1")
            BitcoinNetwork.TEST4 -> appendLine("testnet4=1")
            BitcoinNetwork.SIGNET -> appendLine("signet=1")
            BitcoinNetwork.REGTEST -> appendLine("regtest=1")
        }
        appendLine()

        appendLine("# --- RPC ---")
        appendLine("server=1")
        // No rpcuser/rpcpassword anywhere. Core generates a random cookie at
        // startup and we read it from disk. A password in a config file on a
        // rooted device is a credential sitting in cleartext for no benefit.
        appendLine("rpcbind=127.0.0.1")
        appendLine("rpcallowip=127.0.0.1")
        appendLine("rpcport=$rpcPort")
        // Loopback only. This is the whole reason the app can talk plaintext.
        appendLine("rpcconnect=127.0.0.1")
        appendLine("rpcthreads=4")
        appendLine("rpcworkqueue=64")
        appendLine()

        appendLine("# --- Storage ---")
        if (pruneMb > 0) {
            // Pruning is not optional on a handset. Unpruned mainnet is ~700 GB.
            // Below 550 MB Core refuses to start, so the UI clamps well above it.
            appendLine("prune=$pruneMb")
        }
        if (blockFilterIndex) {
            // BIP158 filters. Costs ~4 GB but makes descriptor rescans over the
            // pruned window fast instead of pathological -- and rescans are what
            // happen every time a user restores a wallet.
            appendLine("blockfilterindex=1")
        }
        // txindex would mean keeping every transaction ever. Flatly incompatible
        // with pruning, and the wallet does not need it.
        appendLine("txindex=0")
        appendLine()

        appendLine("# --- Resources ---")
        // dbcache is the single biggest lever on IBD speed, and also the fastest
        // way to get killed by Android's low-memory killer. Sized from the
        // device's actual RAM in DeviceTuning, not guessed.
        appendLine("dbcache=$dbCacheMb")
        // Core defaults par to "all cores". On an 8-core phone that pins every
        // core to script validation, the SoC thermally throttles, and sync gets
        // *slower* while the device cooks. Two threads is a deliberate ceiling.
        appendLine("par=$parallelScriptChecks")
        appendLine("maxmempool=$maxMempoolMb")
        // Default is 125. Every peer is a socket, a buffer and a wakeup; on
        // mobile the marginal peer past ~12 buys almost no sync speed and costs
        // real battery.
        appendLine("maxconnections=$maxConnections")
        appendLine()

        appendLine("# --- Mobile behaviour ---")
        appendLine(if (listen) "listen=1" else "listen=0")
        // UPnP/NAT-PMP punch holes for inbound connections we do not accept.
        appendLine("upnp=0")
        appendLine("natpmp=0")
        appendLine("discover=0")
        if (blocksOnly) {
            // Data-saver mode. The node stops relaying loose transactions and
            // only takes blocks. Roughly a 10x cut in mobile data, at the cost
            // of an empty local mempool -- so fee estimation degrades and the
            // mempool screen has nothing to show. The UI says so before you
            // turn it on.
            appendLine("blocksonly=1")
        }
        // We never serve BIP37 bloom filters; they are a privacy liability for
        // whoever asks and pure cost for us.
        appendLine("peerbloomfilters=0")
        appendLine("peerblockfilters=${if (blockFilterIndex && listen) 1 else 0}")
        appendLine()

        if (useTor) {
            appendLine("# --- Tor ---")
            appendLine("proxy=127.0.0.1:$torSocksPort")
            if (torOnly) {
                // Refuse clearnet entirely. The strongest privacy posture the
                // node offers: no peer ever sees this device's IP.
                appendLine("onlynet=onion")
            }
            appendLine("dnsseed=0")
            appendLine("listenonion=0")
            appendLine()
        }

        appendLine("# --- Logging ---")
        // We tail debug.log to drive the startup UI, so it must exist and must
        // not also spam stdout (we would be reading the same lines twice).
        appendLine("printtoconsole=0")
        appendLine("debuglogfile=debug.log")
        appendLine("shrinkdebugfile=1")
        appendLine("logtimestamps=1")
        appendLine()

        if (extraArgs.isNotEmpty()) {
            appendLine("# --- User-supplied ---")
            extraArgs.filter { it.isNotBlank() }.forEach { appendLine(it.trim().removePrefix("-")) }
        }
    }

    fun writeTo(dataDir: File): File {
        val f = File(dataDir, "bitcoin.conf")
        f.writeText(render())
        // Core's own datadir permissions are 0700; match them. The datadir is
        // inside app-private storage anyway, but defence in depth costs nothing.
        f.setReadable(false, false)
        f.setReadable(true, true)
        f.setWritable(false, false)
        f.setWritable(true, true)
        return f
    }
}

/**
 * Picks resource limits from the device rather than shipping one guess.
 *
 * A 2019 budget phone with 3 GB of RAM and a 2026 flagship with 16 GB should
 * not run the same dbcache. Getting this wrong in the generous direction gets
 * the process killed mid-sync; getting it wrong in the stingy direction makes
 * initial sync take days.
 */
object DeviceTuning {

    /**
     * Raised across the board after "the download is extremely slow".
     *
     * dbcache is the UTXO set held in RAM. Every megabyte of it is a disk write
     * that does not happen, and on a phone's storage those writes are the
     * bottleneck, not the network. The old tiers were sized to be safe against
     * the low-memory killer; they were so safe the node spent its time
     * flushing. These take roughly 12% of device RAM instead of 5%, which the
     * foreground service's priority comfortably survives.
     */
    fun recommendedDbCacheMb(totalRamMb: Long, isLowRamDevice: Boolean): Int = when {
        isLowRamDevice -> 150
        totalRamMb >= 12_000 -> 2_000
        totalRamMb >= 8_000 -> 1_400
        totalRamMb >= 6_000 -> 900
        totalRamMb >= 4_000 -> 550
        else -> 300
    }

    /**
     * Script verification threads.
     *
     * The old ceiling of 2-3 was set to avoid thermal throttling, and that
     * concern is real — but it was overcorrected. Signature verification is the
     * single most parallel part of validation, and leaving five of eight cores
     * idle to avoid warmth is how a sync takes a week. One core is always left
     * for the OS and the app's own UI.
     */
    fun recommendedScriptThreads(cores: Int): Int =
        (cores - 1).coerceIn(1, 6)

    /**
     * Prune target from free storage, leaving real headroom.
     *
     * The chainstate, the filter index and Android itself all need room the
     * prune target does not account for, and a phone that fills its last byte
     * of storage misbehaves in ways far beyond this app. Never propose more
     * than half of what is free.
     */
    fun recommendedPruneMb(freeBytes: Long): Int {
        val freeMb = freeBytes / (1024 * 1024)
        val half = (freeMb / 2).toInt()
        return half.coerceIn(2_000, 20_000)
    }

    /** Below this, offering an embedded node would be setting the user up to fail. */
    const val MINIMUM_FREE_BYTES_FOR_EMBEDDED: Long = 25L * 1024 * 1024 * 1024
}
